# Site settings
title: Walwood Code It
header-img: img/home-bg.png
email: walwoodr@gmail.com
copyright_name: walwoodr
description: > # this means to ignore newlines until "baseurl:"
  I would code it on a wall, I would code it with you all
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: walwoodr
github_username:  walwoodr
learn_profile: walwoodr
email_username: walwoodr@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
